### ISSUE TITLE
RuntimeError: stft(torch. FloatTensor[1, 119184], n_fft=400, hop_length=2000, win_length=5000, window=torch. FloatTensor{[5000]}, normalized=0, onesided=1, return_complex=0) : expected 0 < win_length <= n_fft, but got win_length=5000。

### ISSUE THREAD

**Issue by lmtmtmt** [BrownsugarZeer/SpectralFeatures#1]
Why do I change it to my own signal, and change the parameter value of LongTermSpectralFlatness and STFT's init , there has some problem.  I don't know why init initialization doesn't seem to have a task effect. These are my parameters.
 def __init__(
        self,
        sample_rate,
        win_length=25,
        hop_length=10,
        n_fft=400,
        window_fn=torch.hamming_window,
        m=10,
        r=30,
        freq_range=None,):
And this is error, I don't know  why n_fft=400, hop_length=2000, win_length=5000, window=torch. FloatTensor{[5000]}.
RuntimeError: stft(torch. FloatTensor[1, 119184], n_fft=400, hop_length=2000, win_length=5000, window=torch. FloatTensor{[5000]}, normalized=0, onesided=1, return_complex=0) : expected 0 < win_length <= n_fft, but got win_length=5000。

**Comment by Jack-ZE-Wu** [comment]
Hi,
What is your sampling rate set to? The sample rate is default to 16000 and `win_length` is default to 25ms. This means our window has 16000 * 25ms = 400 sample points.

I can help you more if you can print the error log or code block.

**Comment by lmtmtmt** [comment]
Thanks!  I misunderstand the unit, now I have solved this problem.
